[tool.poetry]
name = "hypermodern-pypras"
version = "0.1.0"
description = ""
authors = ["Prasetiyo Hadi Purwoko <pras@deuterion.net>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
